spring.application.name=Spring-Security-1

spring.security.user.name=dev
spring.security.user.password=123
#spring.security.user.name=kashi
#spring.security.user.password=kashi@123
#spring.security.user.roles=USER,ADMIN