spring.datasource.url=jdbc:postgresql://localhost:5432/uat_db
spring.datasource.username=uat_user
spring.datasource.password=uat_pass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

app.message=Hello from UAT environment!
server.port=8082