spring.application.name=spring-profiles-demo
app.name=Spring Profiles Demo
app.version=1.0

# Active profile — change this to switch environment
#spring.profiles.active=dev
#spring.profiles.active=prod
#spring.profiles.active=test
spring.profiles.active=uat