spring.application.name=18-SB-Data-JPA

#Postgresql DB config
#spring.datasource.url= jdbc:postgresql://localhost:5432/sb_db
#spring.datasource.username=postgres
#spring.datasource.password=root
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
#
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

#H2 DB config
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url= jdbc:h2:mem:demodb
spring.datasource.username=user
spring.datasource.password=user@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.H2Dialect